server:
  port: 7070   # 服务端口号
spring:
  application:
    name: lovinadminserver     # 服务名称
  security:
    basic:
      enabled: true
    user:
      name: lovin
      password: ${REGISTRY_SERVER_PASSWORD:lovin}
  mail:
    host: smtp.163.com
    username: zzlvexf@163.com
    password: eelve703408
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  boot:
    admin:
      notify:
        mail:
          from: zzlvexf@163.com
          to: zzlvexf@163.com
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user.name: lovin         #These two are needed so that the server
      user.password: lovin #can access the protected client endpoints
  client:
    serviceUrl:
      defaultZone: http://lovin:lovin@localhost:8881/eureka/   # 注册到的eureka服务地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
