server:
  port: 8806   # 服务端口号
spring:
  application:
    name: lovinfeignclient     # 服务名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/   # 注册到的eureka服务地址
feign:
  hystrix:
    enabled: true
